baseurl = "https://code.makery.ch"
title = "code.makery.ch"
pluralizeListTitles = false
preserveTaxonomyNames = true
removePathAccents = true
enableRobotsTXT = true

defaultContentLanguage = "en"

[params]
  intro = "Learning how to code."
  author = "Marco Jakob"
  email = "info@makery.ch"
  analyticsId = "UA-34917397-3"
  disqusShortname = "codemakery"
  googlePlus = "+MarcoJakob7"
  twitter = "codemakery"

[permalinks]
  blog-tag = "/blog/tag/:title/"

[languages]
[languages.en]
  languageName = "English"

[languages.de]
  languageName = "Deutsch"

[languages.es]
  languageName = "Español"

[languages.fa]
  languageName = "فارسی"

[languages.fr]
  languageName = "Français"

[languages.id]
  languageName = "Bahasa Indonesia"

[languages.it]
  languageName = "Italiano"

[languages.kr]
  languageName = "한국어"

[languages.pt]
  languageName = "Português"

[languages.ru]
  languageName = "Русский"

[languages.tr]
  languageName = "Türkçe"

[languages.uk]
  languageName = "Українська"

[languages.zh-cn]
  languageName = "中文（简体）"
